version: 0.2

env:
  variables:
    GRAPHQL_ENDPOINT: 'https://v2.mentorpal.org/graphql'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # to use node 16:
      # - n 16 # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490
      # Install top-level deps
      - NODE_ENV=dev npm ci
      - cd client && npm ci
  pre_build:
    on-failure: ABORT # or CONTINUE
    commands:
      - npm run test:format
      - npm run test:license
      # - cd client && npm run test:audit
      - cd client && npm run test:lint
      - cd client && npm run test:types
      # # cypress tests - we can keep these in github actions?
      # - docker-compose up -d
      # - docker ps
      # - make test-e2e-exec

  build:
    commands:
      - cd client && npm run build

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
